### ISSUE TITLE
Deploy BUDA on our servers

### ISSUE THREAD

**Issue by rodowi** [mxabierto/buda#12]

**Comment by bcessa** [comment]
Con las definiciones de servicio se simplifica el proceso de deploy en cualquier sistema UNIX con soporte para __systemd__ y __docker__.

https://github.com/mxabierto/buda/tree/master/services

Ejemplo:
```
systemctl start buda-storage.service
systemctl start buda-manager.service
systemctl start buda-front.service
```

Revisar el estado de cualquier componente:
```
systemctl status buda-manager.service
```

Seguir los logs conforme van siendo generados en algun componente:
```
journalctl -fu buda-front.service
```
