### ISSUE TITLE
Dockerfile to have a deployment-ready project

### ISSUE THREAD

**Issue by rodowi** [mxabierto/buda#13]

**Comment by rodowi** [comment]
dónde está el PR?

**Comment by bcessa** [comment]
Todos los componentes cuentan con sus dockerfiles:
https://github.com/mxabierto/buda/blob/master/manager/Dockerfile
https://github.com/mxabierto/buda/blob/master/front/Dockerfile
https://github.com/mxabierto/buda/blob/master/agent/build.sh

Y sus definiciones de servicio:
https://github.com/mxabierto/buda/tree/master/services
