### ISSUE TITLE
Add wildcard SSL certificates

### ISSUE THREAD

**Issue by rodowi** [mxabierto/buda#14]

**Comment by bcessa** [comment]
ya tienen listo el certificado para agregarlo al serv? tendría que ser un wildcard para:
__*.datos.gob.mx__

cc @rodowi

**Comment by rodowi** [comment]
todavía no

**Comment by bcessa** [comment]
El soporte para SSL sera terminado en el load balancer que esta montando la gente de KIO/gob.mx por lo que ya no será necesario internamente.
