### ISSUE TITLE
Request for an official domain or subdomain for buda

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/buda#17]

**Comment by carlosmaya** [comment]
@rodowi this is the issue related to the domain
@bcessa we'll need the IP

**Comment by bcessa** [comment]
por el momento quedo con __buda.mxabierto.org__

Los DNS asignados son:
- ns-1318.awsdns-36.org.
- ns-1578.awsdns-05.co.uk.
- ns-133.awsdns-16.com.
- ns-956.awsdns-55.net.
