### ISSUE TITLE
Add DCAT metadata to endpoints

### ISSUE THREAD

**Issue by rodowi** [mxabierto/buda#20]
Es necesario para saber cuándo fue la última versión de los datos, quién me puede solucionar dudas, etc...

www.w3.org/TR/vocab-dcat/
http://adela.datos.gob.mx/inegi/catalogo.json

**Comment by bcessa** [comment]
Una opción es:

- El manager deberá mantener la lista de zonas registradas en el storage principal ( por ejemplo: __sys.zones__ ); por el momento se almacenan unicamente en memoria en tiempo de ejecución  :bomb: :thought_balloon: 
- Los metadatos se mueven del key __metadata__ al __cdat__ y se utilizan los campos estándar para formar la estructura
- Adicionalmente se puede agregar un flag de __active__ a las zonas una vez que estén registradas en el storage, de este modo pueden ser _"apagadas"_ y _"encendidas"_ desde el manager sin necesidad de ser eliminadas
- Otra ventaja de manejar las zonas en el storage es que se pueden hacer __graceful reboots__ 

comentarios?
@mxabierto/core-team

**Comment by chuckcfs** [comment]
del estándar DCAT no conozco demasiado la verdad, pero por lo que entiendo, en el caso de los endpoints de BUDA no es tanto para que este o no relacionado con datos.gob.mx, sino que el estándar establece ciertos metadatos en los datasets como, por ejemplo, en los datasets de ng-ckan: `dcat_modified`, `dcat_publisher_email`, `dcat_publisher_name`

en este caso tienen el prefijo `dcat_` para indicar que esos tags son del estándar DCAT

entonces supongo que a lo que se refiere @rodowi de agregar metadatos DCAT a los endpoints, es ponerle esos parámetros, y tal vez algunos otros del estándar, a la definición de los endpoints
no es que el DCAT de buda este o no relacionado con lo que hay en datos.gob.mx

**Comment by bcessa** [comment]
Consultar PR #29 para comentarios adicionales sobre la integración del DCAT
