### ISSUE TITLE
Definir el API de incidencia delictiva

### ISSUE THREAD

**Issue by iorch** [mxabierto/buda#22]

**Comment by bcessa** [comment]
ya está también la zona: d72738186efed7f0408346c81bb03d96fc105025
https://github.com/mxabierto/buda/blob/master/_zones/incidencia-delictiva.zone

y datos cargados:
http://api.datos.gob.mx/v1/incidenciaDelictiva

cc: @rodowi

**Comment by iorch** [comment]
En incidencia delictiva habrá distintas fuentes, sería bueno que los datos tuvieran de qué fuente provienen. Por ejemplo, lo que cargaste ahí parece ser una lista de delitos, más que un conjunto de datos. 
Copiando a @EduardoClark para que entre en la revisión.

**Comment by bcessa** [comment]
totalmente de acuerdo, de momento no hemos trabajado en las definiciones de los datos y solo estoy agregando campos temporales en las zonas; hace falta revisarlo y definirlo adecuadamente; pero creo no es un tema propiamente del API
