### ISSUE TITLE
Apegarnos al Air Quality Feed Spec v0.9

### ISSUE THREAD

**Issue by rodowi** [mxabierto/buda#24]

**Comment by bcessa** [comment]
@rodowi exactamente que problema hay???

**Comment by rodowi** [comment]
Tiene que ser XML, y siguiendo la v0.9 del estándar.

Schema y ficha técnica están en: https://drive.google.com/drive/folders/0B1jqgLwknF63fjR4LUdvSW5UZjhjaHlKMlBlREJmSVMwMVprUjVIUVpGNV9ZRzNRVFh6Ujg

**Comment by bcessa** [comment]
El buda-front es un API manager, de acuerdo a los estandares que estamos manejando las APIs deberían devolver JSON y solo JSON

https://github.com/mxabierto/api-standards#utiliza-json

Deberíamos comentarlo y buscar una forma de arreglarlo que no sea romper el estándar
cc @rodowi

**Comment by rodowi** [comment]
lo voy a pelear contra el Big Brother, te copio

**Comment by rodowi** [comment]
ya aclaramos el tema de JSON vs XML

pero IMHO esto se cierra hasta que measurements esté dentro del objeto station

**Comment by bcessa** [comment]
Actualizado ahora a la version 0.91 608eaaed8
