### ISSUE TITLE
¿el API debería regresar un metadato con la fecha de la última actualización del endpoint?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/buda#28]
Creo que conforme tengamos más usuarios y endpoints, será necesario describirle al usuario la última versión que representa un endpoint. Imaginemos que en datos.gob.mx el dataset es actualizado cada mes, y el agente de buda no fue sincronizado durante varios meses.

Más que tratar el problema de sincronización recurrente, un tema esencial (creo yo) es proveer un campo de timestamp de última modificación del endpoint.

**Comment by bcessa** [comment]
si, esto se resuelve al mismo tiempo que otro par de temas con la integración del estándar DCAT
PR #29

**Comment by bcessa** [comment]
Cerrado y asignado a #45
