### ISSUE TITLE
Endpoints para nuevo dashboard de www.gob.mx/participa

### ISSUE THREAD

**Issue by rodowi** [mxabierto/buda#39]
Así se va a ver:

![participa_v3_20151204_2](https://cloud.githubusercontent.com/assets/705860/11604617/ad93581c-9ab4-11e5-8c50-cec5f454bdb8.jpg)

**Comment by rodowi** [comment]
De entrada se ven varios endpoints

### Atención ciudadana

1. Los 2 trámites con más peticiones con la cantidad de peticiones (integer)
2. Top 3 de dependencias con más solicitudes (peticiones). Es el nombre de la dependencia y el número de solicitudes (peticiones).
3. La distribución de peticiones por tema, p. ej. Tema 1: 50%, tema 2: 25%, etc... Lo recomendable es que el porcentaje se calcule en el frontend, y que el api traiga el número concreto de peticiones por tema, y el total. Esto nos permitiría tener en mouse-over el número de peticiones por pedazo del Pie chart.

**Comment by rodowi** [comment]
### Consulta

- [ ] Los 2 documentos con más actividad: nombre, número de comentarios, personas que dieron like/approve al doc, unique page views, fecha de cierre del documento.

**Comment by rodowi** [comment]
### Datos abiertos

- [ ] Número de recursos en datos.gob.mx
- [ ] Número de herramientas en [datos.gob.mx/herramientas](http://datos.gob.mx/herramientas/)

**Comment by iorch** [comment]
Sobre lo requerido de Atención ciudadana, me imagino que se quiere esa información con la última base de datos que nos compartieron (para las peticiones), y con la lista de trámites que se buscan en gob mx https://docs.google.com/spreadsheets/d/1GkFKzpYXxQilJl_8LLNU5hVMtFM0JFQ3Epe6F1A9s-k/edit#gid=1562206465&vpid=A1, cierto?

**Comment by rodowi** [comment]
@iorch así es, ver [este link](https://github.com/mxabierto/buda/issues/39#issuecomment-162117999) para mayor información.

**Comment by carlosmaya** [comment]
Para el datos de *Top 4 de los recursos más descargados* 

* ¿Tiene que ser forzosamente sobre las descargas? ¿Sale de algún analytics?

Alternativa o inicialmente podemos sacar a los *conjuntos de datos* mas vistos en los últimos 14 días

http://catalogo.datos.gob.mx/api/3/action/package_search?q=&sort=views_recent+desc&rows=4

**Comment by rodowi** [comment]
@carlosmaya nada es forzoso, es una propuesta validada ese mock. La negociación la lleva @jipster. Sobre ese dato de analytics Carlos Castro.

**Comment by jipster** [comment]
@carlosmaya estamos abiertos a cuáles crees que serían los número más interesantes? quedaría muy fija la info si se trata de las más descargadas históricamente, entonces tendríamos que pensar en las más descargadas de la semana o los más consultados en los últimos 14 días.

**Comment by carlosmaya** [comment]
@jipster perfecto, como propuesta inicial creo que el siguiente dato puede ser interesante

[ ] Top 4 de los conjuntos de datos más populares de los últimas 2 semanas, con su título, dependencia, y fecha de publicación.

**Comment by jipster** [comment]
@iorch qué dices para atención ciudadana de lo que se propuso?

**Comment by iorch** [comment]
@jipster, @rodowi: los links que puse en el comentario de atención ciudadana tiene las tablas con la información requerida. Pueden confirmar que eso es lo que tenían en mente?

**Comment by rodowi** [comment]
@iorch como haremos para tener esta info al día, y cambiando. Será una foto? qué tan seguido se actualizará?
